const data = {
  colors: [
    {
      topBar: 'afb5c2',
      footerBar: '333',
      accent: '719cff',
      bodyText: '333',
      background: 'f6f7f9',
      borders: '999',
      headerText: 'afb5c2',
      buttonText: 'fff',
    },
    {
      topBar: '003459',
      footerBar: 'bcbcbc',
      accent: 'E4B200',
      bodyText: '333',
      background: 'fff',
      borders: 'efefef',
      headerText: '003459',
      buttonText: 'fff',
    },
    {
      topBar: '9FD3BD',
      footerBar: '1B4D59',
      accent: '2ACCCD',
      bodyText: '333',
      background: 'f6f7f9',
      borders: 'efefef',
      headerText: '1B4D592',
      buttonText: 'fff',
    },
    {
      topBar: 'F0E0D5',
      footerBar: 'BB3651',
      accent: '703540',
      bodyText: '333',
      background: 'fff',
      borders: 'efefef',
      headerText: 'BB3651',
      buttonText: 'fff',
    },
    {
      topBar: '003a51',
      footerBar: '02161e',
      accent: 'F0A202',
      bodyText: 'fff',
      background: '00202d',
      borders: 'efefef',
      headerText: 'AFDFF2',
      buttonText: 'fff',
    },
    {
      topBar: 'd6d6d6',
      footerBar: '535455',
      accent: '32A273',
      bodyText: '232323',
      background: 'fff',
      borders: 'd6d6d6',
      headerText: '32A273',
      buttonText: 'fff',
    },
    {
      topBar: '89CCBB',
      footerBar: '342853',
      accent: '78318A',
      bodyText: '232323',
      background: 'fff',
      borders: 'efefef',
      headerText: '337566',
      buttonText: 'fff',
    },
    {
      topBar: '9cdec8',
      footerBar: '45827b',
      accent: '8a1f89',
      bodyText: '232323',
      background: 'fff',
      borders: 'eee',
      headerText: '45827b',
      buttonText: 'fff',
    },
    {
      topBar: '024169',
      footerBar: 'ffdcbb',
      accent: 'ff904a',
      bodyText: '232323',
      background: 'fff',
      borders: 'eee',
      headerText: '024169',
      buttonText: 'fff',
    },
    {
      topBar: '26b7ca',
      footerBar: '30596b',
      accent: 'b5487d',
      bodyText: '232323',
      background: 'fff',
      borders: 'e0f0f2',
      headerText: '30596b',
      buttonText: 'fff',
    },
    {
      topBar: 'b8e1e6',
      footerBar: '36654a',
      accent: '5bc5af',
      bodyText: '232323',
      background: 'fff',
      borders: 'eee',
      headerText: '36654a',
      buttonText: 'fff',
    },
    {
      topBar: '868484',
      footerBar: '2f2f2f',
      accent: 'eab717',
      bodyText: 'fafafa',
      background: '484646',
      borders: 'fafafa',
      headerText: 'eab717',
      buttonText: '2f2f2f',
    },
    {
      topBar: '89acaf',
      footerBar: '3d7871',
      accent: '7fc12d',
      bodyText: '232323',
      background: 'd2ece7',
      borders: '3d7871',
      headerText: '3d7871',
      buttonText: 'fff',
    },
    {
      topBar: '969696',
      footerBar: '500b1a',
      accent: 'd02147',
      bodyText: '232323',
      background: 'dedede',
      borders: 'fafafa',
      headerText: '500b1a',
      buttonText: 'fff',
    },
    {
      topBar: 'bfd3dc',
      footerBar: '34545d',
      accent: 'ffb552',
      bodyText: '232323',
      background: 'fff',
      borders: 'eee',
      headerText: '34545d',
      buttonText: 'fff',
    },
    {
      topBar: 'bbeac0',
      footerBar: '4d5a53',
      accent: '56d4ba',
      bodyText: '232323',
      background: 'fff',
      borders: 'eee',
      headerText: '4d5a53',
      buttonText: 'fff',
    },
    // {
    //   topBar: '',
    //   footerBar: '',
    //   accent: '',
    //   bodyText: '#232323',
    //   background: '#fff',
    //   borders: '#eee',
    //   headerText: '',
    //   buttonText: '#fff',
    // },

    // {
    //   topBar: '',
    //   footerBar: '',
    //   accent: '',
    //   bodyText: '#232323',
    //   background: '#fff',
    //   borders: '#eee',
    //   headerText: '',
    //   buttonText: '#fff',
    // },

    // {
    //   topBar: '',
    //   footerBar: '',
    //   accent: '',
    //   bodyText: '#232323',
    //   background: '#fff',
    //   borders: '#eee',
    //   headerText: '',
    //   buttonText: '#fff',
    // },
    // {
    //   topBar: '',
    //   footerBar: '',
    //   accent: '',
    //   bodyText: '#232323',
    //   background: '#fff',
    //   borders: '#eee',
    //   headerText: '',
    //   buttonText: '#fff',
    // },
    // {
    //   topBar: '',
    //   footerBar: '',
    //   accent: '',
    //   bodyText: '#232323',
    //   background: '#fff',
    //   borders: '#eee',
    //   headerText: '',
    //   buttonText: '#fff',
    // },
  ],
  fonts: [
    {
      mainHeading: 'Lobster, serif',
      subHeading: 'Playfair Display, serif',
      placeholderText: 'Playfair Display, serif',
      subHeadingStyle: 'normal',
      textTransform: 'capitalize',
      bodyFont: 'Open Sans, sans-serif',
      labelText: 'Open Sans'
    },
    // {
    //   mainHeading: 'Playfair Display, serif',
    //   subHeading: 'Lato, sans-serif',
    //   placeholderText: 'Playfair Display, serif',
    //   subHeadingStyle: 'italic',
    //   textTransform: 'uppercase',
    //   bodyFont: 'Open Sans, sans-serif',
    //   labelText: 'Open Sans, sans-serif'
    // },
    // {
    //   mainHeading: 'Playfair Display, serif',
    //   subHeading: 'Lato, sans-serif',
    //   placeholderText: 'Playfair Display, serif',
    //   subHeadingStyle: 'italic',
    //   textTransform: 'uppercase',
    //   bodyFont: 'Open Sans',
    //   labelText: 'Open Sans'
    // }
  ]
}

export default data;

